#version 430 core

layout(local_size_x = 64) in; // Number of threads per work group

struct Particle {
	vec4 position; // xyz: position, w: lifetime
	vec4 velocity; // xyz: velocity, w: rocket
	vec4 color;    // rgba: color
	float life; // Remaining lifetime
	float maxLife; // Maximum lifetime
	vec2 padding; // Padding to align the struct to 16 bytes
};

layout(std430, binding = 0) buffer ParticleBuffer { // Shader Storage Buffer Object (SSBO) for particles. std430 layout allows for more flexible memory layouts.
	Particle particles[];
};

uniform float deltaTime;
uniform float gravity;

void main() {
	uint index = gl_GlobalInvocationID.x; // Gets the index of the current particle

	if (particles[index].maxLife <= 0.0)
		return;

	if (particles[index].life <= 0.0)
		return;

	particles[index].position.xyz += particles[index].velocity.xyz * deltaTime;
	particles[index].velocity.y -= gravity * deltaTime;
	particles[index].life -= deltaTime;

}